modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons ShareAlike 4.0 International (CC BY-SA 4.0) "

[[mods]]
modId="ris3"
version="3.0.0"
displayName="Really In Space 3 b4"
credits="dragonmaster, mrscauthd, pylo, mystiryouswolf, drcrazy"
displayURL="https://youtube.com/c/souldbminer"
logoFile="logo.png"
authors="Souldbminer"

[[dependencies.ris3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




