modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="ris3"
version="0.7.2"
displayName="Really In Space 3.0"
credits="MrScautHD"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Souldbminer"
description='''
Requires Patchuli and Geckolib 3.0 | For Forge and Fabric FML 1.16.4/5   Fabric 1.16.0/1/2/3/4/5
'''

[[dependencies.ris3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ris3]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

