modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons ShareAlike 4.0 International (CC BY-SA 4.0) "

[[mods]]
modId="ris3"
version="3.0.0-RC-1"
displayName="Really In Space 3"
credits="Pylo, Matej, MrScautHD, Golodion, DrCrazy, MrCrayfish"
displayURL="https://youtube.com/c/souldbminer"
logoFile="logo.png"
authors="Souldbminer"
description='''
Requires Obfuscate. Updating to Caves and cliffs when part 2 is realeased
'''

[[dependencies.ris3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ris3]]
    modId="obfuscate"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

